import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, feed, trending, notification
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen bg-black flex">
          <div className="w-[30%] bg-red-700">{children}</div>
          {/* <div className="w-[30%] bg-green-400">{family}</div>
          <div className="w-[30%] bg-emerald-300">{college}</div>
          <div className="w-[10%] bg-blue-500">{school}</div> */}
        </div>
        <div className="bg-black h-screen m-3">{feed}</div>

      </body>
    </html>
  );
}
