import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, feed, analytics, notifications, modal
}: Readonly<{
  children: React.ReactNode;
  feed: React.ReactNode;
  analytics: React.ReactNode;
  notifications: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900`}
      >

        {children}

        <header>
          Parallel Routing Dashboard
        </header>

        <div className="grid grid-cols-4 gap-4 p-6">
          {/* Feed Section */}
          <section className="col-span-2 bg-white rounded-lg p-4 shadow">{feed}</section>

          {/* Analytics */}
          <section className="bg-white rounded-lg p-4 shadow">{analytics}</section>

          {/* Notifications */}
          <section className="bg-white rounded-lg p-4 shadow">{notifications}</section>

          {/* Modals render outside normal flow */}
          {modal}
        </div>
      </body>
    </html>
  );
}
